# Generated by Django 4.1.3 on 2022-12-19 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='base_bid',
        ),
        migrations.RemoveField(
            model_name='item',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cur_bid',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='img',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='mod_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='item',
            name='title',
        ),
        migrations.RemoveField(
            model_name='item',
            name='winner',
        ),
    ]
