# Generated by Django 4.1.3 on 2022-12-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_item_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='winner',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
