# Generated by Django 4.1.3 on 2022-12-19 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_item_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='winner',
        ),
    ]
