# Generated by Django 4.1.3 on 2022-12-19 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='item_id',
            field=models.IntegerField(),
        ),
    ]
